# Maho_4_axes.ini
[EMC]
VERSION = 1.1
MACHINE = MAHO MH400E 4 axis

[HAL]
HALFILE = Maho_4_axes.hal

[TRAJ]
COORDINATES = X Y Z A
LINEAR_UNITS = mm
ANGULAR_UNITS = degree

[KINS]
JOINTS = 4
KINEMATICS = trivkins coordinates=XYZA

#INCLUDE 3Axis_ini.inc
#INCLUDE 4thAxis_ini.inc
