# Maho_3_axes.ini
[EMC]
VERSION = 1.1
MACHINE = MAHO MH400E 3 axis

[HAL]
HALUI = halui
HALFILE = Maho_3_axes.hal
HALFILE = ladder.hal
HALFILE = components/faulthandler/faulthandler.hal
POSTGUI_HALFILE = postgui.hal
HALFILE = components/spindle/fc302_spindle.hal
HALFILE = components/gearbox/mh400e_gearbox.hal
HALFILE = components/toolchange/mh400e_toolchange.hal
HALFILE = components/spindlemaster/mh400e_spindle_master.hal

[TRAJ]
COORDINATES = X Y Z
LINEAR_UNITS = mm
ANGULAR_UNITS = degree
MAX_LINEAR_VELOCITY = 41.667
DEFAULT_LINEAR_VELOCITY = 16.667
NO_FORCE_HOMING = 1

[KINS]
JOINTS = 3
KINEMATICS = trivkins coordinates=XYZ

#INCLUDE 3Axis_ini.inc
