# Maho_3_axes.ini
[EMC]
VERSION = 1.1
MACHINE = MAHO MH400E 3 axis

[HAL]
HALFILE = Maho_3_axes.hal

[TRAJ]
COORDINATES = X Y Z
LINEAR_UNITS = mm
ANGULAR_UNITS = degree
MAX_LINEAR_VELOCITY = 41.667
DEFAULT_LINEAR_VELOCITY = 16.667

[KINS]
JOINTS = 3
KINEMATICS = trivkins coordinates=XYZ

#INCLUDE 3Axis_ini.inc
